image: atlassian/docker-release-maker:latest

pipelines:
  custom:
    new-releases:
      - step:
          name: Bitbucket JDK 8
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='atlassian/bitbucket-server'
            - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
            - export MAC_PRODUCT_KEY='bitbucket'
            - export TAG_SUFFIXES='jdk8,ubuntu'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --create
      - step:
          name: Bitbucket JDK 11
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='false'
            - export DOCKER_REPO='atlassian/bitbucket-server'
            - export DOCKERFILE_BUILDARGS='BASE_IMAGE=adoptopenjdk/openjdk11:slim'
            - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
            - export MAC_PRODUCT_KEY='bitbucket'
            - export TAG_SUFFIXES='jdk11,ubuntu-jdk11'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --create
    jdk8-custom-release:
      - variables:
          - name: BITBUCKET_VERSION
          - name: DOCKER_TAG
      - step:
          services:
            - docker
          script:
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - >
              docker build -t atlassian/bitbucket-server:${DOCKER_TAG}
              --build-arg BITBUCKET_VERSION=${BITBUCKET_VERSION} .
            - docker push atlassian/bitbucket-server:${DOCKER_TAG}
    jdk11-custom-release:
      - variables:
          - name: BITBUCKET_VERSION
          - name: DOCKER_TAG
      - step:
          services:
            - docker
          script:
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - >
              docker build -t atlassian/bitbucket-server:${DOCKER_TAG}
              --build-arg BASE_IMAGE=adoptopenjdk/openjdk11:slim
              --build-arg BITBUCKET_VERSION=${BITBUCKET_VERSION} .
            - docker push atlassian/bitbucket-server:${DOCKER_TAG}
  branches:
    master:
      - step:
          name: Bitbucket JDK 8
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='atlassian/bitbucket-server'
            - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
            - export MAC_PRODUCT_KEY='bitbucket'
            - export TAG_SUFFIXES='jdk8,ubuntu'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --update
      - step:
          name: Bitbucket JDK 11
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='false'
            - export DOCKER_REPO='atlassian/bitbucket-server'
            - export DOCKERFILE_BUILDARGS='BASE_IMAGE=adoptopenjdk/openjdk11:slim'
            - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
            - export MAC_PRODUCT_KEY='bitbucket'
            - export TAG_SUFFIXES='jdk11,ubuntu-jdk11'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --update
  pull-requests:
    '**':
      - step:
          image: python:3.7-alpine3.9
          services:
            - docker
          script:
            - pip install -q -r tests/test-requirements.txt
            - py.test tests/
definitions:
  services:
    docker:
      memory: 2048